package com.jmoordb.core.processor.entity.analizer;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Embedded;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Ignore;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.ViewReferenced;
import com.jmoordb.core.annotation.enumerations.AnnotationType;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import com.jmoordb.core.annotation.enumerations.TypeReferenced;

import javax.lang.model.element.Element;
import javax.lang.model.util.ElementFilter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import javax.annotation.processing.Messager;
import javax.lang.model.element.VariableElement;
import com.jmoordb.core.processor.methods.EntityField;
import com.jmoordb.core.processor.model.EntityData;
import com.jmoordb.core.util.ProcessorUtil;
import java.util.stream.Stream;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

/**
 * 
 * @author avbravo
 * @@code Analiza la anotación @Entity y genera List<EntityField>
 */
public class EntityAnalizer {


    public EntityAnalizer() {
    }



// <editor-fold defaultstate="collapsed" desc="EntityAnalizer get(Element element, Messager messager, String database, TypeMirror typeEntity, List<EntityMethod> entityMethodList)">

    /**
     * Procesa los metodos definidos en la interface
     *
     * @param element
     * @return
     */
    public static EntityAnalizer get(Element element, Messager messager, String database, List<EntityField> entityFieldList, EntityData entityData) {
        LinkedHashMap<String, String> fields = new LinkedHashMap<>();
        List<String> mandatoryFields = new ArrayList<>();

        Stream<VariableElement> stream = ElementFilter.fieldsIn(element.getEnclosedElements()).stream();
        stream.forEach(v -> {
                     Ignore ignore = v.getAnnotation(Ignore.class);
            if (ignore != null) {
/**
 * Campos ignore no se toman en cuenta
 */
                
            }else{
            String nameOfField = v.getSimpleName().toString();

            String type = ProcessorUtil.getTypeOfField(v);

            EntityField entityField = new EntityField.Builder()
                    .nameOfMethod(nameOfField)
                    .returnTypeValue(type)                    
                    .annotationType(AnnotationType.NONE)
                    .returnType(ProcessorUtil.convertToReturnTypeOfField(type))
                    .typeReferenced(TypeReferenced.REFERENCED)
                    
                    .build();

           if(!ProcessorUtil.isValidAnnotationForEntity(v)){
                messager.printMessage(Diagnostic.Kind.ERROR, "Field: " + nameOfField + " You do not have a valid annotation.", element);
                return;
           }
            
           /**
            * 
            */
            final TypeElement classElem = (TypeElement) element;
            final String prefix = System.getProperty("user.dir");
            final String className = classElem.getQualifiedName().toString();
            String fileName = prefix + "/src/main/java/" + className.replace('.', '/') + ".java";

    


            Id id = v.getAnnotation(Id.class);
            if (id != null) {
                entityField.setAnnotationType(AnnotationType.ID);
                entityField.setId(id);
                if (!type.startsWith("java.lang.String") && !type.startsWith("java.lang.Long")) {
                    messager.printMessage(Diagnostic.Kind.ERROR, "Field: " + nameOfField + " Must be of type String or Long.", element);
                }
                if(id.autogeneratedActive().equals(AutogeneratedActive.ON) &&  !type.startsWith("java.lang.Long")){
                    messager.printMessage(Diagnostic.Kind.ERROR, "Field: " + nameOfField + " Autoincrementable is only allowed for Long data types..", element);
                }
                
            }
            Column column = v.getAnnotation(Column.class);
            if (column != null) {
                entityField.setAnnotationType(AnnotationType.COLUMN);
                entityField.setColumn(column);
            }
            Embedded embedded = v.getAnnotation(Embedded.class);
            if (embedded != null) {
             
                entityField.setAnnotationType(AnnotationType.EMBEDDED);
                entityField.setEmbedded(embedded);

            }
            Referenced referenced = v.getAnnotation(Referenced.class);
            if (referenced != null) {

                entityField.setAnnotationType(AnnotationType.REFERENCED);
                entityField.setReferenced(referenced);
                entityField.setTypeReferenced(referenced.typeReferenced());
            }
            
            ViewReferenced viewReferenced = v.getAnnotation(ViewReferenced.class);
            if (viewReferenced != null) {

                entityField.setAnnotationType(AnnotationType.VIEWREFERENCED);
                entityField.setReferenced(viewReferenced);
                entityField.setTypeReferenced(viewReferenced.typeReferenced());
            }

            entityFieldList.add(entityField);
        }
        });

        return new EntityAnalizer();

    }
// </editor-fold>

    


}
