package com.jmoordb.core.processor.builder;

import com.jmoordb.core.annotation.enumerations.GenerationType;
import com.jmoordb.core.annotation.enumerations.ReturnType;
import com.jmoordb.core.annotation.enumerations.TypePK;
import com.jmoordb.core.processor.model.RepositoryData;
import com.jmoordb.core.processor.fields.RepositoryMethod;
import com.jmoordb.core.util.JmoordbCoreUtil;
import com.jmoordb.core.util.MessagesUtil;
import com.jmoordb.core.util.ProcessorUtil;

public class SaveBuilderOld {

    public static final String LINE_BREAK = System.getProperty("line.separator");
    public static String TAB = "   ";
    private String className;

    // <editor-fold defaultstate="collapsed" desc="StringBuilder save(RepositoryData repositoryData)">
    public static StringBuilder save(RepositoryData repositoryData, RepositoryMethod repositoryMethod) {
        StringBuilder builder = new StringBuilder();
        try {

            String param = ProcessorUtil.parametersOfMethod(repositoryMethod);

            String calculateReturn = "";
            String catchReturn = "";

            if (repositoryMethod.getReturnType().equals(ReturnType.OPTIONAL)) {
                if (repositoryData.getGenerationType().equals(GenerationType.OBJECTID)) {

                    calculateReturn += "\tString _id =insertOneResult.getInsertedId().asObjectId().toString();\n";
                    calculateReturn += "\t_id = _id.substring(_id.indexOf(\"{\")+1,_id.indexOf(\"}\"));\n";
                    calculateReturn += "\t_id = _id.replace(\"value=\", \"\");\n";
                    calculateReturn += "\t" + repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(new ObjectId(_id));\n";
                }

                calculateReturn += "return Optional.of(" + repositoryData.getNameOfEntityLower() + ");";
                catchReturn = "return Optional.empty();";
            } else {
                if (repositoryMethod.getReturnType().equals(ReturnType.BOOLEAN)) {
                    calculateReturn = "return Boolean.TRUE;";
                    catchReturn = "return Boolean.FALSE;";
                }
            }
            String autoSetField = "";
            String autoincrementWhileSentence = "";
            String elseAutoincrementWhileSentence = "";
            String returnAutoincrementWhileSentence = calculateReturn + "\n";

            if (repositoryData.getIsAutogenerated() && repositoryData.getTypePK().equals(TypePK.LONG)) {
                autoSetField = repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(repositoryData.getFieldPk()) + "(autogeneratedRepository.generate(mongodbDatabase, mongodbCollection));";

                autoincrementWhileSentence = "\tBoolean success = Boolean.FALSE;\n";
                autoincrementWhileSentence += "\twhile (!success) {\n";
                elseAutoincrementWhileSentence = "\telse{\n";
                elseAutoincrementWhileSentence += "\t\t  success= Boolean.TRUE;\n";
                elseAutoincrementWhileSentence += "\t}\n";
                returnAutoincrementWhileSentence = "";
            } else {

                if (repositoryData.getTypePK().equals(TypePK.STRING)) {

                } else {
                    if (repositoryData.getTypePK().equals(TypePK.OBJECTID)) {

                    } else {
                        if (repositoryData.getTypePK().equals(TypePK.UUID)) {
                            autoSetField = "\tUUID uuid = UUID.randomUUID();\n";
                            autoSetField += "\t" + repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(uuid);\n";

                        }
                    }
                }
            }
            String insertValidation = "";
            String insertOne = "";
            if (repositoryData.getGenerationType().equals(GenerationType.OBJECTID)) {
                insertOne = "               Document doc =" + repositoryData.getNameOfEntityLower() + "Supplier.toDocument(" + repositoryData.getNameOfEntityLower() + ");\n"
                        + "                 doc.remove(\"_id\");\n"
                        + "                 InsertOneResult insertOneResult = collection.insertOne(doc);\n";
            } else {

                insertValidation = "               if (findByPkInternal(" + repositoryData.getNameOfEntityLower() + ".get" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(),mongodbDatabaseValue,  mongodbCollectionValue).isPresent()) { \n"
                        + "                   MessagesUtil.warning(\"There is already a record with that id\");\n"
                        + "                    exception = new JmoordbException(\"There is already a record with that id\");\n"
                        //                    + "                  " + calculateReturn + "\n"
                        + "                " + returnAutoincrementWhileSentence
                        + "               }\n"
                        + "               " + elseAutoincrementWhileSentence;

                insertOne = "               InsertOneResult insertOneResult = collection.insertOne(" + repositoryData.getNameOfEntityLower() + "Supplier.toDocument(" + repositoryData.getNameOfEntityLower() + "));\n";
            }
            String code
                    = ProcessorUtil.editorFold(repositoryMethod, param) + "\n\n"
                    + "    @Override\n"
                    + "    public " + repositoryMethod.getReturnTypeValue() + " " + repositoryMethod.getNameOfMethod() + "(" + param + ") {\n"
                    + "        try {\n"
                    + "               String mongodbDatabaseValue = mongodbDatabase;\n"
                    + "               String mongodbCollectionValue = mongodbCollection;\n"
                    + "               if (!getDynamicDatabase().equals(\"\")) {\n"
                    + "                   mongodbDatabaseValue = getDynamicDatabase();\n"
                    + "                }\n"
                    + "               if (!getDynamicCollection().equals(\"\")) {\n"
                    + "                   mongodbCollectionValue = getDynamicCollection();\n"
                    + "                }\n"
                    + "               MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);\n"
                    + "               setDynamicDatabase(\"\");\n"
                    + "               MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);\n"
                    + "               setDynamicCollection(\"\");\n"
                    + "           MongoCollection<Document> collection = getCollection().get();\n"
                    + "               " + autoincrementWhileSentence
                    + "               " + autoSetField + "\n"
                    + insertValidation + "\n"
                    + insertOne + "\n"
                    + "               if (insertOneResult.getInsertedId() != null) {\n"
                    + "                  " + calculateReturn + "\n"
                    + "               }\n"
                    + "         } catch (Exception e) {\n"
                    + "              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + \" \" + e.getLocalizedMessage());\n"
                    + "               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + \" \" + e.getLocalizedMessage());\n"
                    + "         }\n"
                    + "         " + catchReturn + "\n"
                    + "     }\n"
                    + "// </editor-fold>\n";

            builder.append(code);
        } catch (Exception e) {
            MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
        }
        return builder;
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="StringBuilder saveOfCrud(RepositoryData repositoryData)">
    public static StringBuilder saveOfCrud(RepositoryData repositoryData) {

        // public Optional<T> save(T t);
        StringBuilder builder = new StringBuilder();
        try {

            String nameOfEntityUpper = JmoordbCoreUtil.letterToUpper(repositoryData.getNameOfEntity());
            String nameOfEntityLower = JmoordbCoreUtil.letterToLower(repositoryData.getNameOfEntity());

            String calculateReturn = "";
            String catchReturn = "";

            if (repositoryData.getGenerationType().equals(GenerationType.OBJECTID)) {

                calculateReturn += "\tString _id =insertOneResult.getInsertedId().asObjectId().toString();\n";
                calculateReturn += "\t\t_id = _id.substring(_id.indexOf(\"{\")+1,_id.indexOf(\"}\"));\n";
                calculateReturn += "\t\t_id = _id.replace(\"value=\", \"\");\n";
                calculateReturn += "\t\t" + repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(new ObjectId(_id));\n";
            }

            calculateReturn += "return Optional.of(" + repositoryData.getNameOfEntityLower() + ");";
            catchReturn = "return Optional.empty();";

            String autoSetField = "";
            String autoincrementWhileSentence = "";
            String elseAutoincrementWhileSentence = "";
            String returnAutoincrementWhileSentence = calculateReturn + "\n";

            if (repositoryData.getIsAutogenerated() && repositoryData.getTypePK().equals(TypePK.LONG)) {
                autoSetField = repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(autogeneratedRepository.generate(mongodbDatabase, mongodbCollection));";
                autoincrementWhileSentence = "\tBoolean success = Boolean.FALSE;\n";
                autoincrementWhileSentence += "\twhile (!success) {\n";
                elseAutoincrementWhileSentence = "\telse{\n";
                elseAutoincrementWhileSentence += "\t\t  success= Boolean.TRUE;\n";
                elseAutoincrementWhileSentence += "\t     }\n";
                elseAutoincrementWhileSentence += "\t   }\n";
                returnAutoincrementWhileSentence = "";
            } else {

                if (repositoryData.getTypePK().equals(TypePK.STRING)) {

                } else {
                    if (repositoryData.getTypePK().equals(TypePK.OBJECTID)) {

                    } else {
                        if (repositoryData.getTypePK().equals(TypePK.UUID)) {
                            autoSetField = "\tUUID uuid = UUID.randomUUID();\n";
                            autoSetField += repositoryData.getNameOfEntityLower() + ".set" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(uuid);\n";

                        }
                    }
                }

            }
            String insertValidation = "";
            String insertOne = "";
            if (repositoryData.getGenerationType().equals(GenerationType.OBJECTID)) {
                insertOne = "               Document doc =" + repositoryData.getNameOfEntityLower() + "Supplier.toDocument(" + repositoryData.getNameOfEntityLower() + ");\n"
                        + "                 doc.remove(\"_id\");\n"
                        + "                 InsertOneResult insertOneResult = collection.insertOne(doc);\n";
            } else {

                insertValidation = "               if (findByPkInternal(" + repositoryData.getNameOfEntityLower() + ".get" + JmoordbCoreUtil.letterToUpper(JmoordbCoreUtil.rename_IdToId(repositoryData.getFieldPk())) + "(),mongodbDatabaseValue,  mongodbCollectionValue).isPresent()) { \n"
                        + "                   MessagesUtil.warning(\"There is already a record with that id\");\n"
                        + "                    exception = new JmoordbException(\"There is already a record with that id\");\n"
                        + "                " + returnAutoincrementWhileSentence
                        + "               }\n"
                        + "               " + elseAutoincrementWhileSentence;

                insertOne = "               InsertOneResult insertOneResult = collection.insertOne(" + repositoryData.getNameOfEntityLower() + "Supplier.toDocument(" + repositoryData.getNameOfEntityLower() + "));\n";
            }

            String text = " public Optional<" + nameOfEntityUpper + "> save(" + nameOfEntityUpper + " " + nameOfEntityLower + ")";

            String code
                    = ProcessorUtil.editorFold(text) + "\n\n"
                    + "    @Override\n"
                    + "    public Optional<" + nameOfEntityUpper + "> save(" + nameOfEntityUpper + " " + nameOfEntityLower + ") {\n"
                    + "        try {\n"
                    + "               String mongodbDatabaseValue = mongodbDatabase;\n"
                    + "               String mongodbCollectionValue = mongodbCollection;\n"
                    + "               if (!getDynamicDatabase().equals(\"\")) {\n"
                    + "                   mongodbDatabaseValue = getDynamicDatabase();\n"
                    + "                }\n"
                    + "               if (!getDynamicCollection().equals(\"\")) {\n"
                    + "                   mongodbCollectionValue = getDynamicCollection();\n"
                    + "                }\n"
                    + "               MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);\n"
                    + "               setDynamicDatabase(\"\");\n"
                    + "               MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);\n"
                    + "               setDynamicCollection(\"\");\n"
                    + "               " + autoincrementWhileSentence
                    + "               " + autoSetField + "\n"
                    + insertValidation + "\n"
                    + insertOne + "\n"
                    + "               if (insertOneResult.getInsertedId() != null) {\n"
                    + "                  " + calculateReturn + "\n"
                    + "               }\n"
                    + "         } catch (Exception e) {\n"
                    + "              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + \" \" + e.getLocalizedMessage());\n"
                    + "               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + \" \" + e.getLocalizedMessage());\n"
                    + "         }\n"
                    + "         " + catchReturn + "\n"
                    + "     }\n"
                    + "// </editor-fold>\n";

            builder.append(code);
        } catch (Exception e) {
            MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
        }
        return builder;
    }

    // </editor-fold>
}
